version: "3.8"

services:
  api:
    build:
      context: ./apps/api
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/mydb"

  frontend:
    build:
      context: ./apps/frontend
    ports:
      - "3001:3000"
    depends_on:
      - api

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
