version: "3.8"

services:
  api:
    build:
      context: ./apps/api
    ports:
      - "3200:3200"
    environment:
      DATABASE_URL: "postgresql://postgres:12345@localhost:5432/test-shop?schema=public"

  frontend:
    build:
      context: ./apps/frontend
    ports:
      - "3000:3000"
    depends_on:
      - api

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: test-shop
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
