   # my-turborepo/apps/api/Dockerfile
   FROM node:18

   WORKDIR /usr/src/app
   COPY package*.json ./
   RUN npm install
   COPY . .
   # Логирование переменной окружения
   RUN echo "DATABASE_URL is: $DATABASE_URL"
   RUN npx prisma migrate deploy
   RUN npx prisma generate
   CMD ["npm", "run", "dev"]