   # my-turborepo/apps/api/Dockerfile
   FROM node:18

   WORKDIR /usr/src/app

   COPY package*.json ./
   RUN npm install
   COPY . .
   # Генерация Prisma Client
   RUN npx prisma generate
   CMD ["npm", "run", "dev"]