name: Deploy to Server

on:
  push:
    branches:
      - deploy/dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add SSH known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 80.87.110.203 >> ~/.ssh/known_hosts

      - name: Copy files to server
        run: |
          scp -r ./* root@80.87.110.203:~/my-turborepo

      - name: SSH commands
        run: |
          ssh root@80.87.110.203 << 'EOF'
            cd ~/my-turborepo
            # Удаление неиспользуемых контейнеров и образов
            docker container prune -f
            docker image prune -a -f
            docker-compose down
            echo "DATABASE_URL=postgresql://postgres:12345@db:5432/test-shop?schema=public" > .env
            cat .env
            docker-compose up --build -d
          EOF